### ISSUE TITLE
 develop webvulkan , adopt webgpu or continue with webgl ? 

### ISSUE THREAD

**Issue by GunpowderGuy** [KhronosGroup/WebGLNext-Proposals#1]
https://github.com/KhronosGroup/Vulkan-Docs/issues/451#issuecomment-287398079

**Comment by kenrussell** [comment]
Thanks for asking and raising these issues.

This repository will contain proposals from browser vendors about the shape of the next WebGL API. It will break compatibility with the current API because even with AZDO, there are certain aspects of the OpenGL API which impose overhead which can not be circumvented -- such as mandatory per-draw-call validation. Additionally, the form of certain OpenGL APIs does not mesh well with some of the other native 3D APIs on other operating systems.

Please be patient and wait until the first proposals have been checked in to this repository. Let's begin the technical discussions at that point.
