### ISSUE TITLE
document.getContext()

### ISSUE THREAD

**Issue by f7o** [KhronosGroup/WebGLNext-Proposals#8]
https://github.com/KhronosGroup/WebGLNext-Proposals/blame/master/Obsidian-Mozilla/README.md#L242
Shouldn't this be:
```js
var canvas = document.querySelector("canvas");
var context = canvas.getContext("obsidian-0.1");
```

**Comment by grovesNL** [comment]
The Obsidian context does not need to be attached to a `canvas`, instead it is created from `document`. This behavior is intentional and described in the [readme under API/initialization](https://github.com/KhronosGroup/WebGLNext-Proposals/blame/master/Obsidian-Mozilla/README.md#L226):
> The context obtained from [Document](https://developer.mozilla.org/en/docs/Web/API/Document) is similar to [vkInstance](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkInstance.html): it doesn't provide a single GPU device, but instead allows the user to query available GPUs and work with them manually. The browser can filter out the physically available devices, based on settings, available hardware, and the active power modes. Creating a GPU device also produces the command queues that can execute command buffers.

> The user creates a swap chain manually as well by providing the [Canvas](https://developer.mozilla.org/en/docs/Web/API/Canvas) object. This is different from WebGL, where the context is obtained from the `Canvas`. Disconnecting the context from Canvas allows managing multiple canvases, potentially using different devices and command queues.

In that example, a canvas is used found [later during swapchain creation](https://github.com/KhronosGroup/WebGLNext-Proposals/blame/master/Obsidian-Mozilla/README.md#L257).

**Comment by f7o** [comment]
Thanks! better the readme more carefully.
